/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TugasBAB5;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
/**
 *
 * @author LENOVO
 */
public class GUI_TabelMapelPraktikum extends javax.swing.JFrame {
ArrayList<MataPelajaranPraktikum> listData = new ArrayList<>();

    /**
     * Creates new form GUI_TabelMapelPraktikum
     */
    public GUI_TabelMapelPraktikum() {
        initComponents();
        tampilkanData(); 
 
    }
    private void tampilkanData() {
        DefaultTableModel model = (DefaultTableModel) tabel_data.getModel();
        model.setRowCount(0);
        for (MataPelajaranPraktikum mp : listData) {
            Object[] rowData = {
                mp.cetakKelasAsal(),
                mp.cetakDurasi(),
                mp.cetakJumlahAslab(),
                mp.cetakKelas(),
                mp.cetakLaporan() + " | " +
                mp.cetakAlat() + " | " +
                mp.cetakModul() + " | ",
                mp.cetakStatus()
            };
            model.addRow(rowData);
        }
    }

   private void batal() {
        txtKelasAsal.setText("");
        txtDurasi.setText("");
        txtJumlahAslab.setText("");
        cmb_kelas.setSelectedIndex(0);
        chkLaporan.setSelected(false);
        chkAlat.setSelected(false);
        chkModul.setSelected(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnHapus = new javax.swing.JButton();
        btnCari = new javax.swing.JButton();
        txtCari = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_data = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnUbah = new javax.swing.JButton();
        chkLaporan = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        btnBatal = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnPraktikum = new javax.swing.JButton();
        txtDurasi = new javax.swing.JTextField();
        txtJumlahAslab = new javax.swing.JTextField();
        chkModul = new javax.swing.JCheckBox();
        cmb_kelas = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        chkAlat = new javax.swing.JCheckBox();
        jLabel5 = new javax.swing.JLabel();
        txtKelasAsal = new javax.swing.JTextField();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        btnCari.setText("Cari🔍");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        txtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariActionPerformed(evt);
            }
        });

        tabel_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nama Kelas", "Durasi Kelas", "Jumlah Asleb", "Kelas", "Syarat Lab", "Status"
            }
        ));
        tabel_data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_dataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel_data);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("DATA KELAS PRAKTIKUM");

        jLabel2.setText("Durasi Kelas :");

        jLabel3.setText("Jumlah Asleb :");

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        chkLaporan.setText("Laporan Kegiatan");
        chkLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkLaporanActionPerformed(evt);
            }
        });

        jLabel4.setText("Data Lab :");

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnPraktikum.setText("Form Tabel Praktikum");
        btnPraktikum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPraktikumActionPerformed(evt);
            }
        });

        txtDurasi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDurasiActionPerformed(evt);
            }
        });

        chkModul.setText("Modul Praktikum");
        chkModul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkModulActionPerformed(evt);
            }
        });

        cmb_kelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Fisika", "Biologi", "Kimia", " ", " " }));
        cmb_kelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_kelasActionPerformed(evt);
            }
        });

        jLabel6.setText("Kelas :");

        chkAlat.setText("Ketersediaan Alat");
        chkAlat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkAlatActionPerformed(evt);
            }
        });

        jLabel5.setText("Kelas Asal :");

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtDurasi, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtKelasAsal, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cmb_kelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtJumlahAslab, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(chkAlat, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(chkModul, javax.swing.GroupLayout.PREFERRED_SIZE, 228, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnSimpan)
                        .addGap(49, 49, 49)
                        .addComponent(btnUbah)
                        .addGap(34, 34, 34)
                        .addComponent(btnBatal)
                        .addGap(39, 39, 39)
                        .addComponent(btnHapus)
                        .addGap(27, 27, 27)
                        .addComponent(btnClose)
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 800, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(22, 22, 22))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(126, 126, 126)
                        .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCari)
                        .addGap(32, 32, 32))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnPraktikum)
                        .addGap(83, 83, 83))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnCari)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 21, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtKelasAsal, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtDurasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(txtJumlahAslab, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel6)
                                    .addComponent(cmb_kelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(chkLaporan)
                                .addComponent(jLabel4)))
                        .addComponent(chkAlat)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(chkModul))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnHapus)
                            .addComponent(btnBatal)
                            .addComponent(btnUbah)
                            .addComponent(btnSimpan)
                            .addComponent(btnClose))))
                .addGap(32, 32, 32)
                .addComponent(btnPraktikum)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
       int selectedRow = tabel_data.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih baris yang ingin dihapus.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menghapus data ini?", "Konfirmasi Hapus", JOptionPane.YES_NO_OPTION);
        if (confirm == JOptionPane.YES_OPTION) {
            listData.remove(selectedRow);
            tampilkanData();
            JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
            batal();
        }       // TODO add your handling code here:
    }//GEN-LAST:event_btnHapusActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
    String keyword = txtCari.getText().trim().toLowerCase();

    // Periksa apakah input pencarian kosong
    if (keyword.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Masukkan Kelas praktikum yang ingin dicari.", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return; // Keluar dari method jika input kosong
    }

    DefaultTableModel model = (DefaultTableModel) tabel_data.getModel();
    model.setRowCount(0);
    boolean ditemukan = false;

    for (MataPelajaranPraktikum mp : listData) {
        if (mp.cetakKelas().toLowerCase().contains(keyword) ||
            mp.cetakDurasi().toLowerCase().contains(keyword) ||
            String.valueOf(mp.cetakJumlahAslab()).toLowerCase().contains(keyword) ||
            mp.cetakKelas().toLowerCase().contains(keyword) ||
            (mp.cetakLaporan() + " | " + mp.cetakAlat() + " | " + mp.cetakModul()).toLowerCase().contains(keyword) ||
            mp.cetakStatus().toLowerCase().contains(keyword)) {
            Object[] rowData = {
                mp.cetakKelasAsal(),
                mp.cetakDurasi(),
                mp.cetakJumlahAslab(),
                mp.cetakKelas(),
                mp.cetakLaporan() + " | " +
                mp.cetakAlat() + " | " +
                mp.cetakModul(),
                mp.cetakStatus()
            };
            model.addRow(rowData);
            ditemukan = true;
        }
    }

    if (!ditemukan) {
        JOptionPane.showMessageDialog(this, "Data dengan kata kunci '" + keyword + "' tidak ditemukan.", "Pencarian", JOptionPane.INFORMATION_MESSAGE);
        tampilkanData(); // Tampilkan kembali semua data jika tidak ada yang cocok
    }
    }//GEN-LAST:event_btnCariActionPerformed

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariActionPerformed

    private void tabel_dataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_dataMouseClicked

    }//GEN-LAST:event_tabel_dataMouseClicked

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
        int selectedRow = tabel_data.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih baris yang ingin diubah.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String kelasAsal = txtKelasAsal.getText();
        String durasi = txtDurasi.getText();
        String jumlahAslab = txtJumlahAslab.getText();
        String kelas = (String) cmb_kelas.getSelectedItem();
        String laporan = chkLaporan.isSelected() ? "✓" : "✗";
        String alat = chkAlat.isSelected() ? "✓" : "✗";
        String modul = chkModul.isSelected() ? "✓" : "✗";

        MataPelajaranPraktikum mp = listData.get(selectedRow);
        mp.setKelasAsal(kelasAsal);
        mp.setDurasi(durasi);
        mp.setJumlahAslab(jumlahAslab);
        mp.setKelas(kelas);
        mp.setLaporan(laporan);
        mp.setAlat(alat);
        mp.setModul(modul);
        mp.setStatusOtomatis();

        tampilkanData();
        JOptionPane.showMessageDialog(this, "Data berhasil diubah!");
        batal();
    }//GEN-LAST:event_btnUbahActionPerformed

    private void chkLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkLaporanActionPerformed
      
    }//GEN-LAST:event_chkLaporanActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        // TODO add your handling code here:
        batal();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
         int confirm = JOptionPane.showConfirmDialog(this, "Apakah Anda yakin ingin menyimpan data ini?", "Konfirmasi Simpan", JOptionPane.YES_NO_OPTION);
         if (confirm == JOptionPane.YES_OPTION) {
            String kelasAsal = txtKelasAsal.getText();
            String durasi = txtDurasi.getText();
            String jumlahAslab = txtJumlahAslab.getText();
            String kelas = (String) cmb_kelas.getSelectedItem();
            boolean laporanChecked = chkLaporan.isSelected();
            boolean alatChecked = chkAlat.isSelected();
            boolean modulChecked = chkModul.isSelected();
            String statusPraktikum;
            String laporan = laporanChecked ? "✓" : "✗";
            String alat = alatChecked ? "✓" : "✗";
            String modul = modulChecked ? "✓" : "✗";

       

         if (!laporanChecked && !alatChecked && !modulChecked) {
        statusPraktikum = "DILARANG";
        } else if (laporanChecked && modulChecked && !alatChecked) {
         statusPraktikum = "DILARANG";
        } else if ((laporanChecked ^ alatChecked ^ modulChecked) && 
         !(laporanChecked && alatChecked) && 
         !(laporanChecked && modulChecked) && 
         !(alatChecked && modulChecked)) {
         statusPraktikum = "DILARANG";
        } else {
         statusPraktikum = "DIIZINKAN";
        }


            MataPelajaranPraktikum mp = new MataPelajaranPraktikum();
            mp.setKelasAsal(kelasAsal);
            mp.setDurasi(durasi);
            mp.setJumlahAslab(jumlahAslab);
            mp.setKelas(kelas);
            mp.setLaporan(laporan);
            mp.setAlat(alat);
            mp.setModul(modul);
            mp.dataStatus = statusPraktikum; // Set status langsung di sini

            // Cek apakah data dengan kelas asal yang sama sudah ada
            int indexToUpdate = -1;
            for (int i = 0; i < listData.size(); i++) {
                if (listData.get(i).cetakKelasAsal().equals(kelasAsal)) {
                    indexToUpdate = i;
                    break;
                }
            }

            if (indexToUpdate != -1) {
                listData.set(indexToUpdate, mp); // Update data yang sudah ada
            } else {
                listData.add(mp); // Tambahkan data baru
            }

            tampilkanData();
            JOptionPane.showMessageDialog(this, "Data berhasil disimpan!");
            batal(); // Optional: bersihkan form setelah menyimpan
        }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnPraktikumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPraktikumActionPerformed
    new GUI_TabelMapelPraktikum().setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnPraktikumActionPerformed

    private void txtDurasiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDurasiActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDurasiActionPerformed

    private void cmb_kelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_kelasActionPerformed

        // TODO add your handling code here:
    }//GEN-LAST:event_cmb_kelasActionPerformed

    private void chkAlatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkAlatActionPerformed

    }//GEN-LAST:event_chkAlatActionPerformed

    private void chkModulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkModulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkModulActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
    dispose();       
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_TabelMapelPraktikum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_TabelMapelPraktikum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_TabelMapelPraktikum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_TabelMapelPraktikum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_TabelMapelPraktikum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnPraktikum;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JCheckBox chkAlat;
    private javax.swing.JCheckBox chkLaporan;
    private javax.swing.JCheckBox chkModul;
    private javax.swing.JComboBox<String> cmb_kelas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabel_data;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtDurasi;
    private javax.swing.JTextField txtJumlahAslab;
    private javax.swing.JTextField txtKelasAsal;
    // End of variables declaration//GEN-END:variables
}
