/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TUGAS_BAB_3;

/**
 *
 * @author LENOVO
 */
public class GUI_MataPelajaranPraktikum extends javax.swing.JFrame {

    /**
     * Creates new form GUI_MataPelajaranPraktikum
     */
    public GUI_MataPelajaranPraktikum() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        comboprak = new javax.swing.JComboBox<>();
        txtdurasi = new javax.swing.JTextField();
        txtasleb = new javax.swing.JTextField();
        checkLaporan = new javax.swing.JCheckBox();
        checkAlat = new javax.swing.JCheckBox();
        checkmodul = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Cetak = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        txtkls = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("KELAS  PRAKTIKUM");

        jLabel2.setText("Durasi Kelas :");

        jLabel3.setText("Jumlah Asleb :");

        jLabel4.setText("Praktikum :");

        jLabel5.setText("Data Lab  : ");

        comboprak.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Kimia", "Biologi", "Fisika" }));

        checkLaporan.setText("Laporan Kegiatan");
        checkLaporan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkLaporanActionPerformed(evt);
            }
        });

        checkAlat.setText("Ketersedian Alat");
        checkAlat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkAlatActionPerformed(evt);
            }
        });

        checkmodul.setText("Modul Praktikum");
        checkmodul.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                checkmodulActionPerformed(evt);
            }
        });

        jButton1.setText("Cetak Form ");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        Cetak.setColumns(20);
        Cetak.setRows(5);
        jScrollPane1.setViewportView(Cetak);

        jLabel6.setText("Kelas :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(62, 62, 62)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtdurasi)
                                    .addComponent(txtasleb)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(comboprak, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(0, 0, Short.MAX_VALUE))
                                    .addComponent(txtkls)))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 310, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel5)
                                        .addGap(78, 78, 78)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(checkAlat, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(checkLaporan, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(checkmodul))))
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(155, 155, 155)
                        .addComponent(jButton1)))
                .addContainerGap(38, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(77, 77, 77))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addComponent(jLabel1)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtdurasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtasleb, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtkls, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(comboprak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(checkLaporan))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkAlat)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(checkmodul)
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void checkAlatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkAlatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkAlatActionPerformed

    private void checkLaporanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkLaporanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkLaporanActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
String durasi = txtdurasi.getText();
String aslebStr = txtasleb.getText(); // Dapatkan asleb sebagai String
String kelas = txtkls.getText();
String praktikum = (String) comboprak.getSelectedItem();

int asleb = 0; // Inisialisasi asleb sebagai integer

// Coba ubah aslebStr ke integer
try {
    asleb = Integer.parseInt(aslebStr);
} catch (NumberFormatException e) {
    // Tangani jika aslebStr bukan angka yang valid
    Cetak.setText("Error: Jumlah Asleb harus berupa angka.");
    return; // Keluar dari metode agar tidak terjadi error lebih lanjut
}

// Menentukan bahasa berdasarkan checkbox yang dipilih
String syarat = ""; // Inisialisasi variabel syarat

// Menentukan bahasa berdasarkan checkbox yang dipilih
if (checkLaporan.isSelected() && checkAlat.isSelected() && checkmodul.isSelected()) {
    syarat = "1.Laporan" + "\n"
            + "2.Ketersediaan Alat Lab" + "\n"
            + "3.Modul Praktikum " + "\n"
            + "PRAKTIKUM DAPAT DILAKUKAN";
} else if (checkLaporan.isSelected() && checkAlat.isSelected()) {
    syarat = " 1. Laporan Kegiatan" + "\n"
            + "2. Ketersediaan Alat Lab" + "\n"
            + "PRAKTIKUM DAPAT DILAKUKAN";
} else if (checkLaporan.isSelected() && checkmodul.isSelected()) {
    syarat = " 1. Laporan Kegiatan" + "\n"
            + " 2. Modul Praktikum" + "\n"
            + "PRAKTIKUM DAPAT DILAKUKAN";
} else if (checkAlat.isSelected() && checkmodul.isSelected()) {
    syarat = "1. Ketersediaan Alat " + "\n"
            + "2. Modul Praktikum" + "\n"
            + "PRAKTIKUM DAPAT DILAKUKAN";
} else if (checkLaporan.isSelected()) {
    syarat = "Syarat Praktikum Tidak Terpenuhi" + "\n"
            + " (PRAKTIKUM DILARANG)";
} else if (checkAlat.isSelected()) {
    syarat = "Syarat Praktikum Tidak Terpenuhi" + "\n"
            + " (PRAKTIKUM DILARANG)";
} else if (checkmodul.isSelected()) {
    syarat = "Syarat Praktikum Tidak Terpenuhi" + "\n"
            + " (PRAKTIKUM DILARANG)";
} else {
    syarat = "PRAKTIKUM DILARANG";
}

// Struktur output
String output = "Durasi : " + durasi + "\n" +
        "Jumlah Asleb : " + asleb + "\n" + // asleb sekarang integer
        "Kelas : " + kelas + "\n" +
        "Praktikum : " + praktikum + "\n" +
        "Syarat Praktikum : " + "\n"
        + syarat + "\n";

Cetak.setText(output);     // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void checkmodulActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_checkmodulActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_checkmodulActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_MataPelajaranPraktikum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_MataPelajaranPraktikum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_MataPelajaranPraktikum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_MataPelajaranPraktikum.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_MataPelajaranPraktikum().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea Cetak;
    private javax.swing.JCheckBox checkAlat;
    private javax.swing.JCheckBox checkLaporan;
    private javax.swing.JCheckBox checkmodul;
    private javax.swing.JComboBox<String> comboprak;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtasleb;
    private javax.swing.JTextField txtdurasi;
    private javax.swing.JTextField txtkls;
    // End of variables declaration//GEN-END:variables
}
