/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package TUGASBAB6;
import TugasBAB5.*;
import java.util.ArrayList; import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableColumnModel;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author LENOVO
 */
public class GUI_TabelMapelBahasa extends javax.swing.JFrame {
private List<MataPelajaranBahasa> listData = new ArrayList<>();

    /**
     * Creates new form GUI_TabelMapelBahasa
     */
    public GUI_TabelMapelBahasa() {
        initComponents();
        
        DefaultTableModel dataModel = (DefaultTableModel) tabel_data.getModel();
        int rowCount = dataModel.getRowCount(); 
        while (rowCount > 0) { 
        dataModel.removeRow(rowCount - 1);
        rowCount=dataModel.getRowCount();
        }
    }
        public void batal() {
        txtJam.setText("");
        txtKelas.setText("");
        Inggris.setSelected(false);
        Jepang.setSelected(false);
        cmb_tingkat.setSelectedIndex(0);
        txtMateri.setText("");
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        btnBatal = new javax.swing.JButton();
        btnSimpan = new javax.swing.JButton();
        btnbahasa = new javax.swing.JButton();
        txtJam = new javax.swing.JTextField();
        txtKelas = new javax.swing.JTextField();
        cmb_tingkat = new javax.swing.JComboBox<>();
        btnHapus = new javax.swing.JButton();
        txtMateri = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tabel_data = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnUbah = new javax.swing.JButton();
        Inggris = new javax.swing.JCheckBox();
        Jepang = new javax.swing.JCheckBox();
        jLabel6 = new javax.swing.JLabel();
        btnCari = new javax.swing.JButton();
        txtCari = new javax.swing.JTextField();
        btnClose = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel4.setText("Tingkat Kesulitan :");

        jLabel5.setText("Materi");

        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnSimpan.setText("Simpan");
        btnSimpan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSimpanActionPerformed(evt);
            }
        });

        btnbahasa.setText("Form Tabel Bahasa");
        btnbahasa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnbahasaActionPerformed(evt);
            }
        });

        txtJam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJamActionPerformed(evt);
            }
        });

        cmb_tingkat.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Easy", "Medium", "Hard", " " }));
        cmb_tingkat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmb_tingkatActionPerformed(evt);
            }
        });

        btnHapus.setText("Hapus");
        btnHapus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHapusActionPerformed(evt);
            }
        });

        txtMateri.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtMateriActionPerformed(evt);
            }
        });

        tabel_data.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Durasi Kelas", "Kelas", "Bahasa ", "Tingkat Kesulitan", "Materi"
            }
        ));
        tabel_data.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabel_dataMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tabel_data);

        jLabel1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        jLabel1.setText("DATA KELAS BAHASA");

        jLabel2.setText("Durasi Kelas :");

        jLabel3.setText("Kelas :");

        btnUbah.setText("Ubah");
        btnUbah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUbahActionPerformed(evt);
            }
        });

        Inggris.setText("Inggris");
        Inggris.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                InggrisActionPerformed(evt);
            }
        });

        Jepang.setText("Jepang");

        jLabel6.setText("Bahasa :");

        btnCari.setText("Cari🔍");
        btnCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariActionPerformed(evt);
            }
        });

        txtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariActionPerformed(evt);
            }
        });

        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 237, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnCari)
                        .addGap(127, 127, 127))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtMateri, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel2)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addGap(42, 42, 42)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtKelas, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtJam, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(cmb_tingkat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Jepang, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Inggris, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(btnSimpan)
                                .addGap(26, 26, 26)
                                .addComponent(btnUbah)
                                .addGap(27, 27, 27)
                                .addComponent(btnBatal)
                                .addGap(32, 32, 32)
                                .addComponent(btnHapus)
                                .addGap(18, 18, 18)
                                .addComponent(btnClose))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 647, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(6, 6, 6))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnbahasa)
                        .addGap(23, 23, 23))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(btnCari)
                    .addComponent(txtCari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtJam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel2))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(txtKelas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Inggris)
                            .addComponent(jLabel6))
                        .addGap(5, 5, 5)
                        .addComponent(Jepang)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cmb_tingkat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtMateri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnSimpan)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnHapus)
                        .addComponent(btnClose))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnBatal)
                        .addComponent(btnUbah)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnbahasa)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
     batal();
    }//GEN-LAST:event_btnBatalActionPerformed

    private void btnSimpanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSimpanActionPerformed
      try {
        String jam = txtJam.getText();
        String kelas = txtKelas.getText();
        String materi = txtMateri.getText();
        String tingkat = (String) cmb_tingkat.getSelectedItem();
        String bahasa = "";
        if (Inggris.isSelected()) bahasa += "Inggris";
        if (Jepang.isSelected()) bahasa += "Jepang";

        MataPelajaranBahasa mp = new MataPelajaranBahasa();
        mp.setDataJam(jam);
        mp.setDataKelas(kelas);
        mp.setDataTingkat(tingkat);
        mp.setDataMateri(materi);
        mp.setBahasa(bahasa);

        listData.add(mp);

        DefaultTableModel model = (DefaultTableModel) tabel_data.getModel();
        model.addRow(new Object[]{
            mp.cetakJam(),
            mp.cetakKelas(),
            mp.cetakBahasa(),
            mp.cetakTingkat(),
            mp.cetakMateri()
        });

        JOptionPane.showMessageDialog(this, "Data berhasil disimpan!");
        batal();
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Terjadi kesalahan saat menyimpan data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_btnSimpanActionPerformed

    private void btnbahasaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnbahasaActionPerformed
        new GUI_TabelMapelBahasa().setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_btnbahasaActionPerformed

    private void txtJamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJamActionPerformed

    private void btnHapusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHapusActionPerformed
    // Mendapatkan indeks baris yang dipilih dari tabel
    int selectedRow = tabel_data.getSelectedRow();
    // Jika tidak ada baris yang dipilih (nilai -1), tampilkan peringatan dan keluar dari method
    if (selectedRow == -1) {
        JOptionPane.showMessageDialog(this, "Pilih baris untuk dihapus.", "Peringatan", JOptionPane.WARNING_MESSAGE);
        return;
    }
    // Tampilkan dialog konfirmasi sebelum menghapus
    int konfirmasi = JOptionPane.showConfirmDialog(this, "Yakin hapus data ini?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
    // Jika pengguna memilih "YES", lanjutkan proses hapus
    if (konfirmasi == JOptionPane.YES_OPTION) {
        // Ambil model dari tabel
        DefaultTableModel model = (DefaultTableModel) tabel_data.getModel();

        // Pastikan indeks baris yang dipilih valid dalam listData
        if (selectedRow < listData.size()) {
            // Hapus data dari listData (struktur penyimpanan data utama)
            listData.remove(selectedRow);

            // Hapus baris dari tampilan tabel (ini yang kamu tandai sebagai "KURANG")
            model.removeRow(selectedRow);

            // Tampilkan pesan bahwa data berhasil dihapus
            JOptionPane.showMessageDialog(this, "Data dihapus.", "Sukses", JOptionPane.INFORMATION_MESSAGE);
        } else {
            // Jika terjadi kesalahan indeks (tidak sinkron), tampilkan pesan error
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: Indeks baris tidak valid.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }
    }//GEN-LAST:event_btnHapusActionPerformed

    private void txtMateriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtMateriActionPerformed
      
    }//GEN-LAST:event_txtMateriActionPerformed

    private void tabel_dataMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabel_dataMouseClicked
    //masukkan source code onclick pada tabel
    }//GEN-LAST:event_tabel_dataMouseClicked

    private void btnUbahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUbahActionPerformed
    int selectedRow = tabel_data.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih baris yang ingin diubah.", "Peringatan", JOptionPane.WARNING_MESSAGE);
            return;
        }
        try {
            // Ambil data dari input form
            String jam = txtJam.getText();
            String kelas = txtKelas.getText();
            String materi = txtMateri.getText();
            String tingkat = (String) cmb_tingkat.getSelectedItem();
            String bahasa = "";
            if (Inggris.isSelected()) bahasa += "Inggris ";
            if (Jepang.isSelected()) bahasa += "Jepang";

            // Ambil objek MataPelajaranBahasa yang dipilih
            MataPelajaranBahasa mp = listData.get(selectedRow);

            // Update data objek mp
            mp.setDataJam(jam);
            mp.setDataKelas(kelas);
            mp.setDataMateri(materi);
            mp.setDataTingkat(tingkat);
            mp.setBahasa(bahasa);

            // Update baris di tabel dengan data yang baru
            DefaultTableModel model = (DefaultTableModel) tabel_data.getModel();
            model.setValueAt(mp.cetakJam(), selectedRow, 0);
            model.setValueAt(mp.cetakKelas(), selectedRow, 1);
            model.setValueAt(mp.cetakBahasa(), selectedRow, 2);
            model.setValueAt(mp.cetakTingkat(), selectedRow, 3);
            model.setValueAt(mp.cetakMateri(), selectedRow, 4);
            JOptionPane.showMessageDialog(this, "Data berhasil diubah!");
            batal(); // Bersihkan form input
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnUbahActionPerformed

    private void InggrisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_InggrisActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_InggrisActionPerformed

    private void cmb_tingkatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmb_tingkatActionPerformed

// TODO add your handling code here:
    }//GEN-LAST:event_cmb_tingkatActionPerformed

    private void btnCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariActionPerformed
     String kodeCari = txtCari.getText().trim();

    // Periksa apakah input pencarian kosong
    if (kodeCari.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Masukkan Kelas Bahasa yang ingin dicari.", "Peringatan", JOptionPane.WARNING_MESSAGE);
        System.out.println("Pesan peringatan input kosong ditampilkan."); // Tambahkan untuk debugging
        return;
    }

    // Dapatkan model tabel dan bersihkan tabel sebelum menampilkan hasil pencarian
    DefaultTableModel model = (DefaultTableModel) tabel_data.getModel();
    model.setRowCount(0); // Kosongkan tabel satu kali sebelum loop

    // Flag untuk menandakan apakah data ditemukan
    boolean ditemukan = false;

    // Iterasi seluruh data di listData
    for (int i = 0; i < listData.size(); i++) {
        MataPelajaranBahasa mp = listData.get(i);

        // Cek apakah nilai bahasa (dari method cetakbahasa()) sama dengan yang dicari (case-insensitive)
        if (mp.cetakBahasa().equalsIgnoreCase(kodeCari)) {
            // Buat baris data berdasarkan atribut dari objek
            Object[] row = new Object[]{
                    mp.cetakJam(),
                    mp.cetakKelas(),
                    mp.cetakBahasa(),
                    mp.cetakTingkat(),
                    mp.cetakMateri()
            };
            // Tambahkan baris ke model tabel
            model.addRow(row);
            ditemukan = true;
        }
    }

    // Jika tidak ditemukan satupun data yang cocok, tampilkan pesan
    if (!ditemukan) {
        JOptionPane.showMessageDialog(this, "Data dengan kode tersebut tidak ditemukan.", "Peringatan", JOptionPane.WARNING_MESSAGE);
    }
    }//GEN-LAST:event_btnCariActionPerformed

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
  
    }//GEN-LAST:event_txtCariActionPerformed

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
     dispose();       
    }//GEN-LAST:event_btnCloseActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GUI_TabelMapelBahasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GUI_TabelMapelBahasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GUI_TabelMapelBahasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GUI_TabelMapelBahasa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GUI_TabelMapelBahasa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox Inggris;
    private javax.swing.JCheckBox Jepang;
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnCari;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnHapus;
    private javax.swing.JButton btnSimpan;
    private javax.swing.JButton btnUbah;
    private javax.swing.JButton btnbahasa;
    private javax.swing.JComboBox<String> cmb_tingkat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tabel_data;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtJam;
    private javax.swing.JTextField txtKelas;
    private javax.swing.JTextField txtMateri;
    // End of variables declaration//GEN-END:variables
}
